### ISSUE TITLE
Edit navigation bar buttons color/text and further customization?

### ISSUE THREAD

**Issue by tush4r** [SendOTP/iOS#1]
I cannot customize or edit the navigation bar buttons colors/text and other properties.

**Comment by tush4r** [comment]
@hussain3152 any comments on the changes you did in the SDK for closing the issue?

**Comment by hussain3152** [comment]
Hi Tushar,

You can now also change the navigation bar text colour. 
Rest you can explore the sdk.

Thanks,
Hussain
